#!/usr/bin/env php
<?php

/**
 * MerePHP CLI Bootstrap
 */

defined('BASE_PATH') or define('BASE_PATH', __DIR__);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/merephp/framework/app.php';

$config = require __DIR__ . '/config/console.php';

$application = new mere\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

